<a href="https://colab.research.google.com/github/bysubanji/Python_practice/blob/main/pythonpractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#LISTS
my_lst= [1,3,4,5,7]
print(my_lst)

[1, 3, 4, 5, 7]


In [ ]:
lst= ['my_lst','4','8','hulk']
len(lst)

4

In [ ]:
print(lst)

['my_lst', '4', '8', 'hulk']


In [ ]:
loss_functions=['mean absolute error','mean squared error','huber loss','log loss','hinge loss']


In [ ]:
print(loss_functions[:-3])

['mean absolute error', 'mean squared error']


In [ ]:
# Grab the LAST FOUR elements of the list
print(loss_functions[-4:])

['mean squared error', 'huber loss', 'log loss', 'hinge loss']


In [ ]:
print(loss_functions[-1:])

['hinge loss']


In [ ]:
loss_functions+["wishing"]

['mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss',
 'wishing']

In [ ]:
loss_functions

['mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss']

In [ ]:
## so to make permanent changes we need to re-assign
loss_functions=loss_functions+['something']

In [ ]:
##Its done now
loss_functions

['mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss',
 'something']

In [ ]:
loss_functions=loss_functions*2

In [ ]:
loss_functions

['mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss',
 'something',
 'mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss',
 'something',
 'mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss',
 'something',
 'mean absolute error',
 'mean squared error',
 'huber loss',
 'log loss',
 'hinge loss',
 'something']

In [ ]:
len(loss_functions)

24

In [ ]:
print(min(loss_functions))

hinge loss


In [ ]:
print(max(loss_functions))

something


In [ ]:
new_list = [6, 9, 1, 3, 5.5]
print(sum(new_list))

24.5


In [ ]:
new_list = [6, 9, 1, 3, 5.5]
print(sorted(new_list))

[1, 3, 5.5, 6, 9]


In [ ]:
new_list = [6, 9, 1, 3, 5.5]
print(sorted(new_list,reverse=True))

[9, 6, 5.5, 3, 1]


In [ ]:
new_list.append('2r3')

In [ ]:
#### Appned method changes the list
print(new_list)

[6, 9, 1, 3, 5.5, '2r3']


In [ ]:
new_list.append([1,2,3,4,5])

In [ ]:
print(new_list)

[6, 9, 1, 3, 5.5, '2r3', [1, 2, 3, 4, 5]]


In [ ]:
## Extend 
new_list.extend(['2','3','wubba','lubba','dubba'])

In [ ]:
new_list

[6, 9, 1, 3, 5.5, '2r3', [1, 2, 3, 4, 5], '2', '3', 'wubba', 'lubba', 'dubba']

In [ ]:
##pop method popping off
new_list.pop()

'lubba'

In [ ]:
new_list.pop(3)

5.5

In [ ]:
print(new_list)

[6, 9, 1, '2r3', [1, 2, 3, 4, 5], '2', '3', 'wubba']


In [ ]:
new_list.remove(6)

In [ ]:
new_list

[9, 1, '2r3', [1, 2, 3, 4, 5], '2', '3', 'wubba']

In [ ]:
new_list.clear

<function list.clear>

In [ ]:
new_list

[9, 1, '2r3', [1, 2, 3, 4, 5], '2', '3', 'wubba']

In [ ]:
new_list.count('wubba')

1

In [ ]:
new_list=new_list+[2,3,3]

In [ ]:
new_list

[9, 1, '2r3', [1, 2, 3, 4, 5], '2', '3', 'wubba', '2,3,3', 2, 3, 3]

In [ ]:
new_list.count('2,3,3')

1

In [ ]:
line=[1,1,1,1,2,3,4,5,6,7,8,9,12,2,1,3,]

In [ ]:
line.count(1)

5

In [ ]:
line.index(9)

11

In [ ]:
line.sort()
print(line)

[1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 12]


In [ ]:
line.sort(reverse=True)
print(line)

[12, 9, 8, 7, 6, 5, 4, 3, 3, 2, 2, 1, 1, 1, 1, 1]


In [ ]:
##sort is permanent
line

[12, 9, 8, 7, 6, 5, 4, 3, 3, 2, 2, 1, 1, 1, 1, 1]

In [ ]:
#reverse
line.reverse()
print(line)

[1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 12]


In [ ]:
line1=[1,2,3,4]
line2=['h','i','j']
line=[9,7,5,4]

In [ ]:
lstoflst=[line1,line2,line]
print(lstoflst)

[[1, 2, 3, 4], ['h', 'i', 'j'], [9, 7, 5, 4]]


In [ ]:
lstoflst[2]

[9, 7, 5, 4]

In [ ]:
lstoflst[1][0]

'h'

In [ ]:
lstoflst[2][3]

4

In [ ]:
# Write a Python program to sum all the items in a list.
def sum_list(items):
  sum_numbers=0
  for x in items:
    sum_numbers += x
  return sum_numbers
print(sum_list([2,4,5,6,6]))

23


In [ ]:
##Code to remove duplicate from list using List comprehension 
lstnum = [12, 36, 56, 36, 36, 50, 56, 12]
  
unique_lst = []
[unique_lst.append(ele) for ele in lstnum if ele not in unique_lst]
    
print ("unique elements list  : " ,unique_lst)


unique elements list  :  [12, 36, 56, 50]


In [ ]:
#1
my_list = []

#2
count = int(input("How many numbers you want to add : "))

#3
for i in range(1,count+1):
  my_list.append(int(input("Enter number {} : ".format(i))))

#4
print("Input Numbers : ")
print(my_list)
#5
min = my_list[0]
max = my_list[0]

#6
for no in my_list:
    if no < min :
        min = no
    elif no > max :
        max = no

#7
print("Minimum number : {}, Maximum number : {}".format(min,max))

How many numbers you want to add : 3
Enter number 1 : 1
Enter number 2 : 2
Enter number 3 : 3
Input Numbers : 
[1, 2, 3]
Minimum number : 1, Maximum number : 3


In [ ]:
## Tuples
my_tuple = (3,4,56,'h')

In [ ]:
print(my_tuple)

(3, 4, 56, 'h')


In [ ]:
print(my_tuple[3])

h


In [ ]:
print(my_tuple[1:-1])

(4, 56)


In [ ]:
print(my_tuple.index(3))

0


In [ ]:
print(my_tuple.count(3))

1


In [ ]:
city_list = ['Delhi','Patna','Cuttack','Guwahati']
river_list = ['Yamuna','Ganga','Mahanadi','Brahmaputra']

In [ ]:
city_river_lists= list(zip(city_list,river_list))

In [ ]:
city_river_lists

[('Delhi', 'Yamuna'),
 ('Patna', 'Ganga'),
 ('Cuttack', 'Mahanadi'),
 ('Guwahati', 'Brahmaputra')]

In [ ]:
list(zip(city_list,river_list))


[('Delhi', 'Yamuna'),
 ('Patna', 'Ganga'),
 ('Cuttack', 'Mahanadi'),
 ('Guwahati', 'Brahmaputra')]

In [ ]:
empty_set = set()

In [ ]:
type(empty_set)

set

In [ ]:
# Create a list with repeats
my_list = [1,1,2,2,3,4,5,6,1,1]

In [ ]:
my_uni_list=set(my_list)


##uniques
my_uni_list

{1, 2, 3, 4, 5, 6}

In [ ]:
my_set = {5,7,9,3}

In [ ]:
# add multiple elements
my_set.update([2, 3, 4])
print(my_set)

{2, 3, 4, 5, 7, 9}


In [ ]:
# Make a dictionary with {} and : to signify a key and a value
marvel_dict = {'Name':'Thor','Place':'Asgard','Weapon' : 'Hammer', 1:2, 3 : 'power', 'alibies' : ['Ironman','Captain America'], 'abc' : {1:2, 4:5}}

In [ ]:
print(marvel_dict['Place'])

Asgard


In [ ]:
marvel_dict.keys()

dict_keys(['Name', 'Place', 'Weapon', 1, 3, 'alibies', 'abc'])

In [ ]:
list(marvel_dict.keys())

['Name', 'Place', 'Weapon', 1, 3, 'alibies', 'abc']

In [ ]:
list(marvel_dict.values())

['Thor',
 'Asgard',
 'Hammer',
 2,
 'power',
 ['Ironman', 'Captain America'],
 {1: 2, 4: 5}]

In [ ]:
list(marvel_dict.items())

[('Name', 'Thor'),
 ('Place', 'Asgard'),
 ('Weapon', 'Hammer'),
 (1, 2),
 (3, 'power'),
 ('alibies', ['Ironman', 'Captain America']),
 ('abc', {1: 2, 4: 5})]

In [ ]:
marvel_dict.get('Weapon')

'Hammer'

In [ ]:
country_list = ['India','Australia','United States','England']
city_list = ['New Delhi', 'Canberra' , 'Washington DC','London']

In [ ]:
country_city_list = list(zip(country_list,city_list))

In [ ]:
dict(country_city_list)

{'Australia': 'Canberra',
 'England': 'London',
 'India': 'New Delhi',
 'United States': 'Washington DC'}

In [ ]:
# Let us create a list of paired tuples
country_city_tuples = [('India','New Delhi'),('Australia','Canberra'),('United States','Washington DC'),('England','London')]

In [ ]:
country_city_dict = dict(country_city_tuples)

In [ ]:
country_city_dict

{'Australia': 'Canberra',
 'England': 'London',
 'India': 'New Delhi',
 'United States': 'Washington DC'}

In [ ]:
def count_string(str,chars):
  count=0
  for c in str:
    count += 1 if c in chars else 0

Basic programming

In [ ]:
## Adding two num to get sum
num1= 1
num2=9
sum = num1+num2
print("sum of num1 {0} and num2 {1} is total {2}" .format (num1,num2,sum))

sum of num1 1 and num2 9 is total 10


In [ ]:
# Adding from two input
num1 = input("enter first num: ")
num2 = input("enter second num: ")
sum = float(num1)+float(num2)
print("sum of {0} and {1} is total {2}" .format (num1,num2,sum))

enter first num: 68888888888
enter second num: 11111111111111111111
sum of 68888888888 and 11111111111111111111 is total 1.111111118e+19


In [ ]:
#python programm to find the factorial
def factorial(n):
  return 1 if (n==1 or n==0) else n* factorial(n-1)
  

In [ ]:
num = 5
print(factorial(num))

120


In [ ]:
# find the factorial of n using iterative methods
def factorial(n):
  if n<0:
    return 0
  elif n==0 or n==1:
    return 1
  else:
    fact = 1
    while(n>1):
      fact = n* fact
      n = n-1
    return fact


In [ ]:
num = 5
print(factorial(num))

120


In [ ]:
num = 3
print("Factorial of",num,"is",
factorial(num))

Factorial of 3 is 6


In [ ]:
# Python 3 program to find factorial of given number
import math

def factorial(n):
	return(math.factorial(n))


# Driver Code
num = 9
print("Factorial of", num, "is",
	factorial(num))




Factorial of 9 is 362880


In [ ]:

# Python3 program to find simple interest
# for given principal amount, time and
# rate of interest.


def SIR(p,t,r):
  print("The principal is",p)
  print("The time is",t)
  print("The rate of interest is",r)
  si = (p*t*r)/100

  print("simple interest is", si)
  return si
  

In [ ]:
SIR(2,3,4)

The principal is 2
The time is 3
The rate of interest is 4
simple interest is 0.24


0.24

In [ ]:
## Matrix multiplication 
# Program to multiply two matrices using nested loops

# take a 3x3 matrix
A = [[2,4,5],
     [4,2,1],
     [1,2,3]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]
	
result = [[0, 0, 0, 0],
		[0, 0, 0, 0],
		[0, 0, 0, 0]]

# iterating by row of A
for i in range(len(A)):

	# iterating by column by B
	for j in range(len(B[0])):

		# iterating by rows of B
		for k in range(len(B)):
			result[i][j] += A[i][k] * B[k][j]

for r in result:
	print(r)


[54, 69, 59, 9]
[36, 51, 19, 9]
[29, 37, 34, 5]


In [ ]:
# Program to multiply two matrices (vectorized implementation)

# Program to multiply two matrices (vectorized implementation)

import numpy as np

# take a 3x3 matrix
A = [[2,4,5],
     [4,2,1],
     [1,2,3]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

# result will be 3x4

result= [[0,0,0,0],
		[0,0,0,0],
		[0,0,0,0]]

result = np.dot(A,B)

for r in result:
	print(r)


[54 69 59  9]
[36 51 19  9]
[29 37 34  5]


In [ ]:
# Max array sum
n = int(input())
arr = str(map(int(input().split())))
v =[0]*n
for i in range(n):
  if i < 2:
    v[i]=max(arr[i], 0)
    continue
  elif i==2:
    v[i]=v[i-2]+max(arr[i],0)
    continue
  
v[i] = max(v[i-2], v[i-3]) + max(arr[i], 0)

print(max(v[-1], v[-2]))


2
6


TypeError: ignored

In [ ]:
## Print the repeated alphabet
import collections
the_string=" I will become a data scientist and earn huge money and skills"
results = collections.Counter(the_string)
print(results)

Counter({' ': 12, 'e': 6, 'a': 6, 'n': 5, 'i': 4, 'l': 4, 's': 4, 'd': 3, 't': 3, 'c': 2, 'o': 2, 'm': 2, 'I': 1, 'w': 1, 'b': 1, 'r': 1, 'h': 1, 'u': 1, 'g': 1, 'y': 1, 'k': 1})


In [ ]:
import collections
def string(n):
  return(collections.Counter(n))

In [ ]:
num='i will become a datascientist and earn 6LPA'
print(string(num))

Counter({' ': 7, 'a': 5, 'i': 4, 'e': 4, 't': 3, 'n': 3, 'l': 2, 'c': 2, 'd': 2, 's': 2, 'w': 1, 'b': 1, 'o': 1, 'm': 1, 'r': 1, '6': 1, 'L': 1, 'P': 1, 'A': 1})


In [ ]:
# Fibonacci 
n = int(input("Enter the nth value: "))
a = 0
b = 1
sum = 0
print("Fibonacci Series : ", end = " ")
while(sum <= n):
     print(sum, end = " ")
     a = b
     b = sum
     sum = a + b


Enter the nth value: 2
Fibonacci Series :  0 1 1 2 

In [ ]:
got_houses = ['Stark', 'Arryn', 'Baratheon', 'Tully', 'Greyjoy', 'Lannister', 'Tyrell', 'Martell', 'Targaryen']

In [ ]:
for house in got_houses[::-1]:
  print(f"house {house}")


house Targaryen
house Martell
house Tyrell
house Lannister
house Greyjoy
house Tully
house Baratheon
house Arryn
house Stark


In [ ]:
for number, house in enumerate(got_houses):
  print(f'house no is {house} is {number+1}')

house no is Stark is 1
house no is Arryn is 2
house no is Baratheon is 3
house no is Tully is 4
house no is Greyjoy is 5
house no is Lannister is 6
house no is Tyrell is 7
house no is Martell is 8
house no is Targaryen is 9


In [ ]:
# The list of numbers
list_of_numbers = [1, 2, 4, 6, 11, 14, 17, 20]

In [ ]:
for number in list_of_numbers:
  sq_num = number**2
  print(f'sq of the {number} is {sq_num}')

sq of the 1 is 1
sq of the 2 is 4
sq of the 4 is 16
sq of the 6 is 36
sq of the 11 is 121
sq of the 14 is 196
sq of the 17 is 289
sq of the 20 is 400


In [ ]:
list_of_numbers

[1, 2, 4, 6, 11, 14, 17, 20]

In [ ]:
sqrnum=[]

for number in list_of_numbers:
  sq = number**2
  sqrnum.append(sq)
print(f'list of sq of num is {sqrnum}')

list of sq of num is [1, 4, 16, 36, 121, 196, 289, 400]


In [ ]:
zipdict=dict(zip(list_of_numbers,sqrnum))
zipdict

{1: 1, 2: 4, 4: 16, 6: 36, 11: 121, 14: 196, 17: 289, 20: 400}

In [ ]:
for number in list_of_numbers:
  if number%2==0:
    sqr_num = number**2
    print(f'the {number} of is {sqr_num}')
  else:
    print(f'i am an odd {number} ')

i am an odd 1 
the 2 of is 4
the 4 of is 16
the 6 of is 36
i am an odd 11 
the 14 of is 196
i am an odd 17 
the 20 of is 400


In [ ]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [ ]:
for number in range (2,12,3):
  sq_numbr=number**2
  print(f'sq of {number} is {sq_numbr}')


sq of 2 is 4
sq of 5 is 25
sq of 8 is 64
sq of 11 is 121


In [ ]:
sum_sq = 0

for number in range(0,12):
  sum_sq += number**2
  print(sum_sq)

0
1
5
14
30
55
91
140
204
285
385
506


In [ ]:
# Let us first store the sentence in a string variable 
heisenberg_quote =  "I am the one who knocks!"

In [ ]:
for char in heisenberg_quote:
  print(f" The character is {char}")

 The character is I
 The character is  
 The character is a
 The character is m
 The character is  
 The character is t
 The character is h
 The character is e
 The character is  
 The character is o
 The character is n
 The character is e
 The character is  
 The character is w
 The character is h
 The character is o
 The character is  
 The character is k
 The character is n
 The character is o
 The character is c
 The character is k
 The character is s
 The character is !


In [ ]:
# Lets apply a for loop to do the above task

for index,char  in enumerate(heisenberg_quote):
  print(f" The index is {index} and the character is {char}")

 The index is 0 and the character is I
 The index is 1 and the character is  
 The index is 2 and the character is a
 The index is 3 and the character is m
 The index is 4 and the character is  
 The index is 5 and the character is t
 The index is 6 and the character is h
 The index is 7 and the character is e
 The index is 8 and the character is  
 The index is 9 and the character is o
 The index is 10 and the character is n
 The index is 11 and the character is e
 The index is 12 and the character is  
 The index is 13 and the character is w
 The index is 14 and the character is h
 The index is 15 and the character is o
 The index is 16 and the character is  
 The index is 17 and the character is k
 The index is 18 and the character is n
 The index is 19 and the character is o
 The index is 20 and the character is c
 The index is 21 and the character is k
 The index is 22 and the character is s
 The index is 23 and the character is !


In [ ]:
x = 0
while x<10:
  print('x is currently: ',x)
  print('x is less than 10, adding 1 to x')
  x=x+1

x is currently:  0
x is less than 10, adding 1 to x
x is currently:  1
x is less than 10, adding 1 to x
x is currently:  2
x is less than 10, adding 1 to x
x is currently:  3
x is less than 10, adding 1 to x
x is currently:  4
x is less than 10, adding 1 to x
x is currently:  5
x is less than 10, adding 1 to x
x is currently:  6
x is less than 10, adding 1 to x
x is currently:  7
x is less than 10, adding 1 to x
x is currently:  8
x is less than 10, adding 1 to x
x is currently:  9
x is less than 10, adding 1 to x


In [ ]:
sq_nu=[number **2 for number in list_of_numbers]
sq_nu

[1, 4, 16, 36, 121, 196, 289, 400]

In [ ]:
sq_num = [number**2 for number in list_of_numbers if number%2==0]
sq_num

[4, 16, 36, 196, 400]

In [ ]:
lk=[1,2,3,2,1,3,4,5,6,6,6]
m=set(lk)
m

{1, 2, 3, 4, 5, 6}

In [ ]:
od_sq=[number**2 if number%2!=0 else number**3 for number in list_of_numbers]
od_sq

[1, 8, 64, 216, 121, 2744, 289, 8000]

In [ ]:
heisenberg_quote = "It ceases to exist without me. No, you clearly don't know who you're talking to, so let me clue you in. I am not in danger, Skyler. I am the danger."

In [ ]:
words_by_walter = heisenberg_quote.split(' ')
first_letter = [word[0] for word in words_by_walter]
print(first_letter)

['I', 'c', 't', 'e', 'w', 'm', 'N', 'y', 'c', 'd', 'k', 'w', 'y', 't', 't', 's', 'l', 'm', 'c', 'y', 'i', 'I', 'a', 'n', 'i', 'd', 'S', 'I', 'a', 't', 'd']


In [ ]:
def extract_first_letters(sentence):
  word_in_sentence = sentence.split(' ')
  first_letters = [word[0] for word in word_in_sentence]
  return first_letters

In [ ]:
extract_first_letters(heisenberg_quote)

['I',
 'c',
 't',
 'e',
 'w',
 'm',
 'N',
 'y',
 'c',
 'd',
 'k',
 'w',
 'y',
 't',
 't',
 's',
 'l',
 'm',
 'c',
 'y',
 'i',
 'I',
 'a',
 'n',
 'i',
 'd',
 'S',
 'I',
 'a',
 't',
 'd']

In [ ]:
def factorial(num):
  if num<0:
    print(f'factorial is not defined for zero')
  elif num>0:
    result=1
    for i in range(1,num+1):
      result= result*i
  else:
    print(f'the factoril of 0 is 1')

  return result

In [ ]:
num =(factorial(9))
num

362880

In [ ]:
def number_char(string):
  total=0
  for char in string:
    total = total+1
  return total

In [ ]:
original_string = "The quick brown rhino jumped over the extremely lazy fox."
print(number_char(original_string))

57


In [ ]:
t

In [ ]:
def assignQuarter(user_date):
  
  date_year = user_date[:4]
  date_month = user_date[5:7]

  # Step 2 : Store the quarter value in a string variable named quarter
  if (date_month >= '01') & (date_month <='03'):
    quarter = date_year + '-Q1'
  elif (date_month >= '04') & (date_month <='06'):
    quarter = date_year + '-Q2'
  elif (date_month >= '07') & (date_month <='09'):
    quarter = date_year + '-Q3'
  else:
    quarter = date_year + '-Q4'

  # Step 3 : Print the message you want to display to the user. Here we are not returning anything  
  print(f'The corresponding quarter for the date {user_date} is {quarter}')
  # return quarter

In [ ]:
smp = '27-09-2021'
dq_quarter = assignQuarter(smp)
print(dq_quarter)

The corresponding quarter for the date 27-09-2021 is 27-0-Q4
None


In [ ]:
def check_even_odd(num):
  if num%2==0:
    return 'even'
  return 'odd'

In [ ]:
chck = check_even_odd(8)
print(chck)

even


In [ ]:
heights =  [172,175,170,168,170,200]

In [ ]:
def calculate_avg(my_list):
  mean = sum(my_list)/len(my_list)
  sorted_list= sorted(my_list)
  list_length=len(sorted_list)

  if list_length%2==0:
    median = (sorted_list[int(list_length/2)-1] + sorted_list[int(list_length/2)])/2
  else:
    median = sorted_list[int((list_length+1)/2)-1]
  return mean, median

In [ ]:
h=[2,3,4,5]
calculate_avg(h)

(3.5, 3.5)

In [ ]:
# Python Program to Count Occurrence of a Character in a String

def count_Occurrence(ch, str1):
    count = 0
    for i in range(len(string)):
        if(string[i] == char):
            count = count + 1
    return count

string = input("Please enter your own String : ")
char = input("Please enter your own Character : ")

cnt = count_Occurrence(char, string)
print("The total Number of Times ", char, " has Occurred = " , cnt)

Please enter your own String : hi how are u
Please enter your own Character : h
The total Number of Times  h  has Occurred =  2


In [ ]:
def count_ocr(ch,str2):
  count=0
  for i in range(len(string)):
    if(string[i] == char):
      count = count+1
  return count

string = input('enter your string: ')
char = input('enter you character: ')

cnt = count_ocr(char, string)
print("total num of times" ,char, "has occrd = " ,cnt)


enter your string: please god this time execute my programme successfully
enter you character: s
total num of times s has occrd =  5


In [ ]:
from collections import Counter

input_string = "Data Science will give me success"

frequency_per_char = Counter(input_string)

# Show Output
print ("Per char frequency in '{}' is :\n {}".format(input_string, str(frequency_per_char)))

Per char frequency in 'Data Science will give me success' is :
 Counter({' ': 5, 'e': 5, 'c': 4, 'i': 3, 's': 3, 'a': 2, 'l': 2, 'D': 1, 't': 1, 'S': 1, 'n': 1, 'w': 1, 'g': 1, 'v': 1, 'm': 1, 'u': 1})
Type of frequency_per_char is:  <class 'collections.Counter'>


In [ ]:
print(frequency_per_char)

Counter({' ': 5, 'e': 5, 'c': 4, 'i': 3, 's': 3, 'a': 2, 'l': 2, 'D': 1, 't': 1, 'S': 1, 'n': 1, 'w': 1, 'g': 1, 'v': 1, 'm': 1, 'u': 1})


In [ ]:
def factorial(n):
  return 1 if (n==1 or n==0) else n* factorial(n-1)

In [ ]:

## Define char num in string
from collections import Counter
def char_count(n):
  return (Counter(n))

In [ ]:
n= 'helo i will get job'
print(char_count(n))

Counter({' ': 4, 'l': 3, 'e': 2, 'o': 2, 'i': 2, 'h': 1, 'w': 1, 'g': 1, 't': 1, 'j': 1, 'b': 1})


In [ ]:
# xercise 1: Print First 10 natural numbers using while loop
i =1 
while i<=10:
  print(i)
  i = i+1

1
2
3
4
5
6
7
8
9
10


In [ ]:
print("Number Pattern ")

# Decide the row count. (above pattern contains 5 rows)
row = 5
for i in range(1, row + 1, 1):
    # Run inner loop i+1 times
    for j in range(1, i + 1):
        print(j, end=' ')
    # empty line after each row
    print(" ")


Number Pattern 
1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


In [ ]:
# Python 3 code to find sum
# of elements in given array
def _sum(arr,n):
	
	# return sum using sum
	# inbuilt sum() function
	return(sum(arr))


In [ ]:
num=[1,2,3,4]
n=len(num)
print(_sum(num,n))

10


In [ ]:
n = 2
for i in range(1,11,1):
  product=n*i
  print(product)

2
4
6
8
10
12
14
16
18
20


In [ ]:
numbers = [12, 75, 150, 180, 145, 525, 50]
for item in numbers:
  if item>500:
    break
  elif item>150:
    continue
  elif item%5==0:
    print(item)

75
150
145


In [ ]:
# Consider a list of strings 

got_houses = ['Stark', 'Arryn', 'Baratheon', 'Tully', 'Greyjoy', 'Lannister', 'Tyrell', 'Martell', 'Targaryen']

In [ ]:
for house in got_houses[::-1]:
  
  print(house)

Targaryen
Martell
Tyrell
Lannister
Greyjoy
Tully
Baratheon
Arryn
Stark


In [ ]:
list_of_numbers=[1, 2, 4, 6, 11, 14, 17, 20]

In [ ]:
sq_num = [number **2 for number in list_of_numbers]
print(list_of_numbers)
print(sq_num)

[1, 2, 4, 6, 11, 14, 17, 20]
[1, 4, 16, 36, 121, 196, 289, 400]


In [ ]:
sq_even = [number**2 for number in list_of_numbers if number %2==0]
print(f"the sq of  is {sq_even}")

the sq of  is [4, 16, 36, 196, 400]


In [ ]:
for number in list_of_numbers:
  if number%2==0:
    sq_num= number**2
    print(f"The sq of {number} is {sq_num}")
  else:
    print(f"I am an odd {number} and my master not allow me to get squared")

I am an odd 1 and my master not allow me to get squared
The sq of 2 is 4
The sq of 4 is 16
The sq of 6 is 36
I am an odd 11 and my master not allow me to get squared
The sq of 14 is 196
I am an odd 17 and my master not allow me to get squared
The sq of 20 is 400


In [ ]:
list(range(0,10))

for number in range(0,10):
  sq_num= number**2
  print(f"the sq of num is {sq_num}")

the sq of num is 0
the sq of num is 1
the sq of num is 4
the sq of num is 9
the sq of num is 16
the sq of num is 25
the sq of num is 36
the sq of num is 49
the sq of num is 64
the sq of num is 81


In [ ]:
for i in range(0,10):
  if i%2==0:
    sum=i
    print(sum)
  else:
    print(f"odd")
  

0
odd
2
odd
4
odd
6
odd
8
odd


In [ ]:
# Let us the initialize the sum of the squares with 0. This makes sense right!
sum_squares = 0

for number in range(1,11):
  sum_squares = sum_squares + number**2
  print(sum_squares)

# Now we have added the squares of all the numbers in our list
print(f"The sum of the squares of our list of numbers is {sum_squares}")

1
5
14
30
55
91
140
204
285
385
The sum of the squares of our list of numbers is 385


In [ ]:
heisenberg_quote =  "I am the one who knocks!"

In [ ]:
for char in heisenberg_quote:
  print(f"the chaaracter is {char}")

the chaaracter is I
the chaaracter is  
the chaaracter is a
the chaaracter is m
the chaaracter is  
the chaaracter is t
the chaaracter is h
the chaaracter is e
the chaaracter is  
the chaaracter is o
the chaaracter is n
the chaaracter is e
the chaaracter is  
the chaaracter is w
the chaaracter is h
the chaaracter is o
the chaaracter is  
the chaaracter is k
the chaaracter is n
the chaaracter is o
the chaaracter is c
the chaaracter is k
the chaaracter is s
the chaaracter is !


In [ ]:
for index, char in enumerate(heisenberg_quote):
  print(f"The {index} of {char}")

The 0 of I
The 1 of  
The 2 of a
The 3 of m
The 4 of  
The 5 of t
The 6 of h
The 7 of e
The 8 of  
The 9 of o
The 10 of n
The 11 of e
The 12 of  
The 13 of w
The 14 of h
The 15 of o
The 16 of  
The 17 of k
The 18 of n
The 19 of o
The 20 of c
The 21 of k
The 22 of s
The 23 of !


In [ ]:
heisenberg_quote = "It ceases to exist without me. No, you clearly don't know who you're talking to, so let me clue you in. I am not in danger, Skyler. I am the danger."

In [ ]:
words= heisenberg_quote.split(' ')
print(words)

['It', 'ceases', 'to', 'exist', 'without', 'me.', 'No,', 'you', 'clearly', "don't", 'know', 'who', "you're", 'talking', 'to,', 'so', 'let', 'me', 'clue', 'you', 'in.', 'I', 'am', 'not', 'in', 'danger,', 'Skyler.', 'I', 'am', 'the', 'danger.']


In [ ]:
for word in words:
  if word not in ['I', 'you']:
    print(word)

It
ceases
to
exist
without
me.
No,
clearly
don't
know
who
you're
talking
to,
so
let
me
clue
in.
am
not
in
danger,
Skyler.
am
the
danger.


In [ ]:
days = ('Monday' ,'Tuesday' ,'Wednesday' ,'Thursday' ,'Friday','Saturday','Sunday')
for day in days:
  print(f"today is {day}")

today is Monday
today is Tuesday
today is Wednesday
today is Thursday
today is Friday
today is Saturday
today is Sunday


In [ ]:
country_city_dict = {'India': 'New Delhi', 'Australia': 'Canberra', 'United States': 'Washington DC', 'England': 'London'}
for item in country_city_dict:
  print(item)

India
Australia
United States
England


In [ ]:
list_of_numbers = [1, 2, 4, 6, 11, 14, 17, 20]


In [ ]:
sq_n =[]
for number in list_of_numbers:
  sq_n.append(number**2)
print(f"the sq of th num is {sq_n}")

the sq of th num is [1, 4, 16, 36, 121, 196, 289, 400]


In [ ]:
sq_n = [number **2 for number in list_of_numbers]
sq_n

[1, 4, 16, 36, 121, 196, 289, 400]

In [ ]:
odd_sq=[number **2 for number in list_of_numbers if number%2!=0]
odd_sq

[1, 121, 289]

In [ ]:
n=[number**2 if number%2==0 else number**1 for number in list_of_numbers]
n

[1, 4, 16, 36, 11, 196, 17, 400]

In [ ]:
list(range(4))
lst = []
for num1 in range(4):
  for num2 in range(3):
    lst.append(num1)
lst

[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]

In [ ]:
lstf = [num1 for num1 in range(4) for num2 in range(2) ]
lstf

[0, 0, 1, 1, 2, 2, 3, 3]

In [ ]:
lst_of_list = []

for num1 in range(4):
  lst_of_list.append([])
  for num2 in range(3):
    lst_of_list[num1].append(num2)
print(lst_of_list)


[[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [ ]:
lst_f = [[num2 for num2 in range(4)] for num1 in range(2)]
lst_f

[[0, 1, 2, 3], [0, 1, 2, 3]]

In [ ]:
country_city_list = [('India','New Delhi'),('Australia','Canberra'),('United States','Washington DC'),('England','London')]

In [ ]:
country_city_dict = dict(country_city_list)

In [ ]:
# The conventional for loop approach
flipped = {}
for country, city in country_city_dict.items():
    flipped[city] = country

print(flipped)

{'New Delhi': 'India', 'Canberra': 'Australia', 'Washington DC': 'United States', 'London': 'England'}


In [ ]:
flip ={city:country for country, city in country_city_dict.items()}
flip

{'Canberra': 'Australia',
 'London': 'England',
 'New Delhi': 'India',
 'Washington DC': 'United States'}

In [ ]:
heisenberg_quote = "It ceases to exist without me. No, you clearly don't know who you're talking to, so let me clue you in. I am not in danger, Skyler. I am the danger."

In [ ]:
words_walter= heisenberg_quote.split(' ')
words_walter

['It',
 'ceases',
 'to',
 'exist',
 'without',
 'me.',
 'No,',
 'you',
 'clearly',
 "don't",
 'know',
 'who',
 "you're",
 'talking',
 'to,',
 'so',
 'let',
 'me',
 'clue',
 'you',
 'in.',
 'I',
 'am',
 'not',
 'in',
 'danger,',
 'Skyler.',
 'I',
 'am',
 'the',
 'danger.']

In [ ]:
def frst(sentence):
  words=sentence.split(' ')
  frt=[word[0] for word in words]
  return frt

In [ ]:
print(frst(heisenberg_quote))

['I', 'c', 't', 'e', 'w', 'm', 'N', 'y', 'c', 'd', 'k', 'w', 'y', 't', 't', 's', 'l', 'm', 'c', 'y', 'i', 'I', 'a', 'n', 'i', 'd', 'S', 'I', 'a', 't', 'd']


In [ ]:
from collections import Counter
def something(n):
  return Counter(n)

In [ ]:
n = 'Hi '
print(something(n))

Counter({'H': 1, 'i': 1, ' ': 1})


In [ ]:
def factorial(num):
  if num<0:
    print(f"No factorial for negative num")
  elif num>0:
    result = 1
    for i in range(1,num+1,1):
      result = result*i
  else:
        print(f"factorial of the num 0 is 1")
  return result

In [ ]:
num=(factorial(6))
print(num)

720


In [ ]:
def odd_ev(num):
  if num%2==0:
    return 'even'
  else:
    return 'odd'

In [ ]:
num=4
print(odd_ev(num))

even


In [ ]:
def lstap(mylist,elem):
  new_list=mylist+[elem]
  return new_list


In [ ]:
import numpy as np

In [ ]:
prime_array = np.array([1,2,3,5,7])
print(prime_array)

[1 2 3 5 7]


In [ ]:
an= np.array([[1,2],[3,4]])
an

array([[1, 2],
       [3, 4]])

In [ ]:

import numpy as np

# 1d array to list
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')


In [ ]:
## array to list
lst= an.tolist()
print(type(lst))
print(lst)

<class 'list'>
[[1, 2], [3, 4]]


In [ ]:
## uninitialised array
n = np.empty([3,5],dtype=int)
n

array([[     93899827242112,        214748364850,        206158430253,
               193273528372,        223338299440],
       [       206158430292,        249108103220,        244813135921,
               227633266746,        197568495671],
       [       236223201332,        206158430260,        206158430259,
        8242750738829148250, 2318265722715728997]])

In [ ]:
m = np.zeros((2,2))
m

array([[0., 0.],
       [0., 0.]])

In [ ]:
b= np.ones((1,3))
b

array([[1., 1., 1.]])

In [ ]:
lst=[3,4,5]
arr = np.asarray(lst)
arr

array([3, 4, 5])

In [ ]:
arr[:1]


array([3])

In [ ]:
# getting the entire array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[0:2]) 


[[1 2 3]
 [4 5 6]]


In [ ]:
# Create a 2 D Array
arravali = np.array(np.random.randint(10,15,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[14 10]
 [11 13]
 [14 10]
 [10 11]
 [12 11]
 [11 12]
 [10 14]
 [11 12]]
 
 The shape of the array is (8, 2)


In [ ]:
n=np.transpose(arravali)
n

array([[14, 11, 14, 10, 12, 11, 10, 11],
       [10, 13, 10, 11, 11, 12, 14, 12]])

In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,4], index=['a','b','c','d','e'],name='si')
s


a    1
b    2
c    3
d    4
e    4
Name: si, dtype: int64

In [ ]:
# Creating our first DataFrame
some_2D_array = np.random.randint(4, 6,(3,4))
first_dataframe = pd.DataFrame(some_2D_array , columns=['Akshay','Devashish','Divy','Monika'])
first_dataframe

Akshay  Devashish  Divy  Monika
0       5          4     5       4
1       5          4     5       5
2       4          4     5       5

In [ ]:
s = np.random.randint(3,5,(2,3))
fd = pd.DataFrame(s, columns=['a','b','c'])
fd

a  b  c
0  3  4  3
1  3  4  4

In [ ]:
s = np.random.randint(3,5,(2,3))
fd = pd.DataFrame(s, columns=['a','b','c'],index=['1','2'])
fd

a  b  c
1  3  4  4
2  4  4  3

In [ ]:
sr = {'fd' : pd.Series([1,2,3,4]),
      'sd' : pd.Series([4,3,2,1])}
ss=pd.DataFrame(sr)
ss

fd  sd
0   1   4
1   2   3
2   3   2
3   4   1

In [ ]:
a=2
b=3

In [ ]:
lst= a*b
lst

6

In [ ]:
lst=[2,3,4,5,6]

In [ ]:
sq = [number **2 for number in lst]
print(sq)

[4, 9, 16, 25, 36]
